name: vy_translation
description: A way to manage message translations even from other packages (that use vy_translation ...)
version: 0.2.4
homepage: https://github.com/giorgiofran/vy_translation
publish_to: none

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  yaml: any
  recase: any
  quiver: any
  dart_style: any
  dart_console: any
  vy_lock: #^1.6.0
    git:
      url: "https://github.com/giorgiofran/vy_lock"

  vy_language_tag: ^0.1.3

  vy_analyzer_utils:
    git:
      url: "https://github.com/giorgiofran/vy_analyzer_utils"

  vy_dart_meme:
    git:
      url: "https://github.com/giorgiofran/vy_dart_meme"

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0

