name: vy_translation
version: 0.2.4
description: A way to manage message translations even from other packages (that use vy_translation ...)
homepage: "https://github.com/giorgiofran/vy_translation"

dependencies:
  dart_console: 1.0.0
  dart_style: 1.3.10
  quiver: 2.1.5
  recase: 4.0.0
  vy_analyzer_utils:
    git: "https://github.com/giorgiofran/vy_analyzer_utils"
  vy_dart_meme:
    git: "https://github.com/giorgiofran/vy_dart_meme"
  vy_language_tag: 0.1.5
  vy_lock:
    git: "https://github.com/giorgiofran/vy_lock"
  yaml: 2.2.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0

environment:
  sdk: ">=2.7.1 <3.0.0"
